# Generated by Django 4.2.3 on 2025-02-21 15:58

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('description', django_cryptography.fields.encrypt(models.TextField())),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
