# Generated by Django 4.2.3 on 2025-02-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do', '0001_initial'),
    ]

    operations = [
    ]
