# Generated by Django 4.2.3 on 2025-02-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do', '0002_auto_20250222_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title_plain',
            field=models.CharField(default='Default Task Title', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
