# Generated by Django 4.2.3 on 2025-02-22 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do', '0003_task_title_plain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title_plain',
        ),
    ]
