# Generated by Django 4.2.3 on 2025-02-22 04:30

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do', '0005_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(default='Default Task Title', max_length=255, unique=True)),
        ),
    ]
