# Generated by Django 4.2.3 on 2025-02-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do', '0008_alter_task_description_alter_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
