# Generated by Django 4.2.3 on 2025-02-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do', '0009_remove_task_completed_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
