# Generated by Django 4.2.3 on 2025-02-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do', '0010_task_completed_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
